Fix yaml indentation on DBT guide
Error:
```
$ dbt run            
12:21:48  Running with dbt=1.1.1
12:21:48  Partial parse save file not found. Starting full parse.
12:21:50  Encountered an error:
Compilation Error in model actor_summary (models/actors/actor_summary.sql)
  Model 'model.imdb.actor_summary' (models/actors/actor_summary.sql) depends on a source named 'imdb.genres' which was not found
```

Example of `schema.yml` from DBT's docs:
https://docs.getdbt.com/reference/configs-and-properties#example